apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-app
  namespace: multi-cloud-dr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-app
  template:
    metadata:
      labels:
        app: azure-app
    spec:
      containers:
        - name: azure-app
          image: multi-cloud-dr-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: CLOUD_PROVIDER
              value: "AZURE"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-app
  namespace: multi-cloud-dr
spec:
  selector:
    app: azure-app
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP